Rating component
rutu14/Component-Library pull request #11
Opened 2022-02-15 16:57 UTC by rutu14

Preview: https://deploy-preview-11--friendly-kilby-44e498.netlify.app/documentation/rating.html

2022-02-15 17:54 UTC, zoyatanweer commented on components/component.css
remove spaces

2022-02-15 17:55 UTC, zoyatanweer approved these changes
good to merge. great UI

2022-02-15 17:58 UTC, itsmebipul00 approved these changes

2022-02-16 02:52 UTC, zoef-yt requested changes

2022-02-16 02:52 UTC, zoef-yt commented on documentation/css/prism-custom.css
> +    color: #d19a66;
use var for colours

2022-02-16 06:20 UTC, rutu14 commented on components/component.css
Sure

2022-02-16 06:21 UTC, rutu14 commented on documentation/css/prism-custom.css
> +    color: #d19a66;
Thanks for the reminder.

2022-02-16 06:26 UTC, merged